# Generated by Django 3.1.5 on 2022-06-04 12:12

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pics/blog')),
                ('category', models.CharField(max_length=200)),
                ('Content', froala_editor.fields.FroalaField()),
                ('Date', models.DateField()),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('rating', models.CharField(choices=[('8', 'Half Star Rating'), ('15', 'One Star Rating'), ('29', 'One and Half Star Rating'), ('40', 'Two Star Rating'), ('48', 'Two and Half Star Rating'), ('60', 'Three Star Rating'), ('68.25', 'Three and Half Star Rating'), ('80', 'Four Star Rating'), ('88', 'Four and Half Star Rating'), ('100', 'Five Star Rating')], max_length=150)),
                ('photo', models.ImageField(upload_to='pics/book-review')),
                ('review', froala_editor.fields.FroalaField()),
                ('categories', models.CharField(max_length=500)),
                ('Tags', models.CharField(max_length=200)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='pics/genres')),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner_upper_tagline', models.CharField(max_length=200)),
                ('Banner_lower_tagline', models.CharField(max_length=200)),
                ('Banner_first_line', models.CharField(max_length=50)),
                ('Banner_second_line', models.CharField(max_length=50)),
                ('About_Me_heading_paragraph', models.TextField()),
                ('banner_image', models.ImageField(upload_to='pics/about')),
                ('About_me', froala_editor.fields.FroalaField()),
                ('linked_by', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.bookreview')),
            ],
        ),
        migrations.CreateModel(
            name='PopularBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.bookreview')),
            ],
        ),
        migrations.AddField(
            model_name='bookreview',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.genre'),
        ),
    ]
