# Generated by Django 3.1.5 on 2022-06-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='Facebook_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='Footer_bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='Instagram_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='Pinterest_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='Twitter_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
